### ISSUE TITLE
Ir Implementation links dead

### ISSUE THREAD

**Issue by evilknivel** [cenobitedk/esphome_multical402#1]
Hi,

sadly the links to the schematics for the ir Implementation are broken can you provide more informations?

**Comment by evilknivel** [comment]
This link to the ebay store works

https://www.ebay.de/usr/arelektronik

**Comment by cenobitedk** [comment]
Sorry I didn't see this issue. I haven't able to find the original post, but this one might help. It's in Danish so you'll need to translate the page with google chrome or something else.
https://wiki.hal9k.dk/projects/kamstrup

**Comment by cenobitedk** [comment]
Honestly though, I don't think it's viable to build your own when the ones on ebay are that cheap. If you have a 3D printer you can get the pcb alone which is only 8 EUR.

**Comment by cenobitedk** [comment]
I have updated the readme with the link as well.
