### ISSUE TITLE
Multical 403 on ESP32

### ISSUE THREAD

**Issue by SkyumP** [cenobitedk/esphome_multical402#4]
I had timeout problems on some registers with this code. 

Debugging showed two gave timeout and therefore other registers didn’t come through.   

Increasing timeout property in the code to 250 solved it. 

Thanks for the great work 👍

**Comment by SkyumP** [comment]
My Multical 403 is also reporting Energy in kWh and not MWh as stated in the ESP code.

**Comment by cenobitedk** [comment]
Good to hear the timeout solved it!
I believe these modules behave differently, so I'm not surprised you had to tweak the value. The different register ID's are available in the 402 module technical sheet (https://documentation.kamstrup.com/docs/MULTICAL_402/en-GB/Technical_description/CONT37B1606E19044A7E972030DA2B41B890/?page=82) but not in the 403 module (https://documentation.kamstrup.com/docs/MULTICAL_403/en-GB/Technical_description/CONT46E54F336D7047A7907749B26DD3576C/?page=130). But I'm expecting the register ID's should be the same for these 2 modules.

It's technically possible to read out the unit (see chapter 5 here: https://github.com/nabovarme/MeterLoggerTesto/blob/master/5512447_M1_GB.pdf) but the code didn't have support for it and I didn't have time to add it, hence the need to specify the unit of measure in the esphome config (https://github.com/cenobitedk/esphome_multical402#unit-of-measurement).
