### ISSUE TITLE
New sources for optical ir reader

### ISSUE THREAD

**Issue by Nelus82** [cenobitedk/esphome_multical402#6]
Do you have new sources to get a optical reader?

**Comment by Nelus82** [comment]
Maybe this: https://www.ebay.nl/itm/275076138187?hash=item400bd0c4cb:g:VxwAAOSwbkdhxLJL&amdata=enc%3AAQAIAAAA4BrzvzYG9z1z8ruhswvdBHqKCPDEy05bsZEGsAIpMp2lWs5BcOiYEHxuInXDYzP0A8q1YeZ3K%2B5m3KsoB4ywFE6lAhjirA1H%2B3SBqcRQDRUcEzS%2B7mpmqg2rcFMhvftc%2F0mxiMZFkZr499NqOgzuCTXB9%2FVF6gj3JOQ0YD4XDdopmwgbnH%2F%2FDFHVE3Eu3RXJp84a40GtZROegM8wANg%2FhmeGnb%2BIKC8jPenYGtUU5oX8hgJRTPbxwcDl6tztnYnddEeyH4wFlBoutHEBsstM4t7H9qXDDiImpVuDdui7Iruv%7Ctkp%3ABk9SR7aMiND5Yg

**Comment by bobvandevijver** [comment]
I have ordered this one, I will try to let you know whether it works!

**Comment by htvekov** [comment]
There are multiple sellers where you can get these IR D0 optical readers

https://www.ebay.de/itm/313460034498?mkcid=1&mkrid=707-53477-19255-0&siteid=77&campid=5338920542&customid=&toolid=20012&mkevt=1

and

https://www.ebay.de/itm/305130184344?_trkparms=amclksrc%3DITM%26aid%3D1110006%26algo%3DHOMESPLICE.SIM%26ao%3D1%26asc%3D257001%26meid%3D999b9c4bda7a4feabbadbcf85c7d858e%26pid%3D101195%26rk%3D3%26rkt%3D12%26sd%3D313460034498%26itm%3D305130184344%26pmt%3D1%26noa%3D0%26pg%3D4429486%26algv%3DSimPLWebV1EmbeddedAuctionsCPCAuto%26brand%3DMarkenlos&_trksid=p4429486.c101195.m1851&amdata=cksum%3A305130184344999b9c4bda7a4feabbadbcf85c7d858e%7Cenc%3AAQAIAAABAKQWTaSuKxcpq1j5hG%252Bz9F%252B8zK5%252FOpV48i2l8raehpQf%252BmHXMZTC30utUIplUNOb1vbvm4W2Tg8X%252FInCAYk8mNleu26b0G9RNWVNoJn8yDS3IdiHZgFLwHpCt%252FrNWRa9mSM6%252FRv7A6Y7P0ac1aOFJCls7YwPv5qeDVlk4Fg9MzEqJhMxdYyt%252FtZjesvW4G7%252BBV33pWp7pGlqBZpynCV30hI0dtJJ9mKVf1EdzB75FAkSf%252FLr5tG8KufHKX92c9GtX4FI48VnTjaiMzdiLYqJ0CEFVOxEkhdno4OYj2RAJrh4xz6P%252F%252FccMRzEGnQNqe2c3HDon96RBYVVzKTCcKxfdLw%253D%7Campid%3APL_CLK%7Cclp%3A4429486

**Comment by bobvandevijver** [comment]
> I have ordered this one, I will try to let you know whether it works!

I can confirm this one works! You will need to solder the LED and transistor yourself and put it together, but it works :)

**Comment by cenobitedk** [comment]
@Nelus82 I have believe you've found a good replacement, and I have just added the links to the readme. :-)

Thanks to @bobvandevijver and @htvekov for helping out!
